name: Compiler
on:
    push:
      - 'GUET-Thesis.cls'
    branches: [ main ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Download Fonts
        run: |
          chmod +x ${{ github.workspace }}/Fonts/download_fonts.sh
          ${{ github.workspace }}/Fonts/download_fonts.sh
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          texlive_version: latest
          latexmk_use_xelatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf